project:
  name: quickstart-ibm-icp-for-data
  shorten_stack_name: true
  s3_regional_buckets: true
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-central-1
  - eu-north-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-south-1
  - sa-east-1
  - ca-central-1
  
  s3_bucket: ''
tests:

  1AZ-wkc-ocs:
    parameters:
      WKC: 'True'
      OCSInstanceType: r5.4xlarge
      NumberOfAZs: '1'
      AvailabilityZones: $[taskcat_genaz_1]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: m5a.4xlarge
      NumberOfMaster: '1'
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
    regions:  
    - ca-central-1
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

#  1AZ-wml-px:
#    parameters:
#      WML: 'True'
#      NumberOfAZs: '1'
#      AvailabilityZones: $[taskcat_genaz_1]
#      VPCCIDR: 10.0.0.0/16
#      ComputeInstanceType: r5.4xlarge
#      LicenseAgreement: I agree
#      ClusterName: $[taskcat_random-string]
#      StorageType: Portworx
#      Namespace: zenpx
#      ICPDDeploymentLogsBucketName: override
#      QSS3BucketName: $[taskcat_autobucket]
#      QSS3BucketRegion: $[taskcat_current_region]
#      DomainName: override
#      AdminPassword: override
#      APIKey: override
#      APIUsername: override
#      KeyPairName: override
#      BootNodeAccessCIDR: override
#      RedhatPullSecret: override
#      PortworxSpec: override
#    regions:  
#    - ap-south-1
#    s3_bucket: ''
#    template: templates/ibm-cloudpak-root.template.yaml

#  3AZ-os-ocs:
#    parameters:
#      OpenScale: 'True'
#      NumberOfAZs: '3'
#      AvailabilityZones: $[taskcat_genaz_3]
#      VPCCIDR: 10.0.0.0/16
#      LicenseAgreement: I agree
#      ClusterName: $[taskcat_random-string]
#      Namespace: zen
#      ICPDDeploymentLogsBucketName: override
#      QSS3BucketName: $[taskcat_autobucket]
#      QSS3BucketRegion: $[taskcat_current_region]
#      DomainName: override
#      AdminPassword: override
#      APIKey: override
#      APIUsername: override
#      KeyPairName: override
#      BootNodeAccessCIDR: override
#      RedhatPullSecret: override
#    regions:
#    - ap-southeast-1
#    s3_bucket: ''
#    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-wml-dv-px:
    parameters:
      WML: 'True'
      DV: 'True'
      EnableFips: 'True'
      NumberOfAZs: '3'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: r5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: Portworx
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - ap-northeast-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-wkc-px:
    parameters:
      WKC: 'True'
      EnableFips: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: r5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: Portworx
      Namespace: pxzen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - eu-west-3
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-dv-cde-spark-efs:
    parameters:
      DV: 'True'
      CDE: 'True'
      Spark: 'True'
      EnableFips: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: c5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: EFS
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - eu-west-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

#  3AZ-wkc-wsl-efs:
#    parameters:
#      WKC: 'True'
#      WSL: 'True'
#      AvailabilityZones: $[taskcat_genaz_3]
#      VPCCIDR: 10.0.0.0/16
#      LicenseAgreement: I agree
#      ClusterName: $[taskcat_random-string]
#      StorageType: EFS
#      Namespace: zen
#      ICPDDeploymentLogsBucketName: override
#      QSS3BucketName: $[taskcat_autobucket]
#      QSS3BucketRegion: $[taskcat_current_region]
#      DomainName: override
#      AdminPassword: override
#      APIKey: override
#      APIUsername: override
#      KeyPairName: override
#      BootNodeAccessCIDR: override
#      RedhatPullSecret: override
#    regions:
#    - eu-west-1
#    s3_bucket: ''
#    template: templates/ibm-cloudpak-root.template.yaml

#  1AZ-wsl-os-ocs:
#    parameters:
#      WSL: 'True'
#      OpenScale: 'True'
#      OCSInstanceType: r5.4xlarge
#      NumberOfAZs: '1'
#      AvailabilityZones: $[taskcat_genaz_1]
#      VPCCIDR: 10.0.0.0/16
#      ComputeInstanceType: r5.4xlarge
#      NumberOfMaster: '1'
#      LicenseAgreement: I agree
#      ClusterName: $[taskcat_random-string]
#      Namespace: zen
#      ICPDDeploymentLogsBucketName: override
#      QSS3BucketName: $[taskcat_autobucket]
#      QSS3BucketRegion: $[taskcat_current_region]
#      DomainName: override
#      AdminPassword: override
#      APIKey: override
#      APIUsername: override
#      KeyPairName: override
#      BootNodeAccessCIDR: override
#      RedhatPullSecret: override
#    regions:
#    - us-west-1
#    s3_bucket: ''
#    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-wkc-spark-efs:
    parameters:
      WKC: 'True'
      Spark: 'True'
      EnableFips: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: EFS
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - us-west-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-wkc-dv-px:
    parameters:
      DV: 'True'
      WKC: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: r5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: Portworx
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - us-east-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-wkc-cde-ocs:
    parameters:
      WKC: 'True'
      CDE: 'True'
      NumberOfAZs: '3'
      NumberOfMaster: '3'
      OCSInstanceType: r5.4xlarge
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
    regions:  
    - us-east-1
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml


              
    
