project:
  name: quickstart-ibm-icp-for-data
  shorten_stack_name: true
  s3_regional_buckets: true
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-central-1
  - eu-north-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-south-1
  - sa-east-1
  - ca-central-1
  
  s3_bucket: ''
tests:

  1AZ-wkc-ocs:
    parameters:
      WKC: 'True'
      OCSInstanceType: r5.4xlarge
      NumberOfAZs: '1'
      AvailabilityZones: $[taskcat_genaz_1]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: m5a.4xlarge
      NumberOfMaster: '3'
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
    regions:  
    - us-west-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-spark-ocs:
    parameters:
      Spark: 'True'
      EnableFips: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - eu-central-1
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-cde-private-efs:
    parameters:
      CDE: 'True'
      EnableFips: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: c5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: EFS
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
      PrivateCluster: "Internal"
    regions:  
    - eu-west-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml 

  1AZ-OS-efs:
    parameters:
      OpenScale: 'True'
      NumberOfAZs: '1'
      AvailabilityZones: $[taskcat_genaz_1]
      VPCCIDR: 10.0.0.0/16
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: EFS
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
    regions:  
    - us-west-1
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  1AZ-WML-c4-px:
    parameters:
      WML: 'True'
      EnableFips: 'True'
      StorageType: 'Portworx'
      NumberOfAZs: '1'
      AvailabilityZones: $[taskcat_genaz_1]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: c5.4xlarge
      NumberOfMaster: '3'
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      Namespace: cpdtest
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
    regions:  
    - us-east-2
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  3AZ-wsl-px:
    parameters:
      WSL: 'True'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      ComputeInstanceType: r5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: Portworx
      Namespace: zenpx
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - eu-west-1
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml

  1AZ-lite-private-px:
    parameters:
      AvailabilityZones: $[taskcat_genaz_1]
      VPCCIDR: 10.0.0.0/16
      NumberOfAZs: 1
      ComputeInstanceType: r5.4xlarge
      LicenseAgreement: I agree
      ClusterName: $[taskcat_random-string]
      StorageType: Portworx
      Namespace: zen
      ICPDDeploymentLogsBucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      DomainName: override
      AdminPassword: override
      APIKey: override
      APIUsername: override
      KeyPairName: override
      BootNodeAccessCIDR: override
      RedhatPullSecret: override
      PortworxSpec: override
    regions:  
    - ap-south-1
    s3_bucket: ''
    template: templates/ibm-cloudpak-root.template.yaml


              
    
