apiVersion: metaoperator.cpd.ibm.com/v1
kind: CPDService
metadata:
  name: ${SERVICE}-cpdservice
  labels:
    app.kubernetes.io/instance: ibm-cp-data-operator-${SERVICE}-cpdservice
    app.kubernetes.io/managed-by: ibm-cp-data-operator
    app.kubernetes.io/name: ibm-cp-data-operator-${SERVICE}-cpdservice
spec:
  serviceName: "${SERVICE}"
  version: "latest"
  storageClass: "${STORAGECLASS}"
  overrideConfig: "${override-storage}"
  flags: ""
  autoPatch: false
  scale: ""
  optionalModules: []
  license: 
    accept: true
