apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 15-security-limits
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,KiBoYXJkIG5vZmlsZSA2NjU2MAoqIHNvZnQgbm9maWxlIDY2NTYw
        filesystem: root
        mode: 0644
        path: /etc/security/limits.conf
